### ISSUE TITLE
Switch Onboarding Form link to a button to be better highlighted

### ISSUE THREAD

**Issue by manuelbarbas** [skalenetwork/docs.skale.space#114]
**Describe the bug**
The onboarding from link needs to be highlighted due to its importance 

**Screenshots**

<img width="548" alt="Screenshot 2024-07-22 at 20 01 08" src="https://github.com/user-attachments/assets/0f4bdc52-7f8e-4519-82f5-bf4a0fcc17eb">

**Comment by TheGreatAxios** [comment]
Completed in previous push
