### ISSUE TITLE
Sidebar scrolls up when topic is selected

### ISSUE THREAD

**Issue by manuelbarbas** [skalenetwork/docs.skale.space#79]
When some topic of the sidebar is selected the sidebar automatically scrolls all the way up and believe it shouldn't

**Example:**

- User slects on the following sidebar topic:

<img width="311" alt="Screenshot 2024-04-01 at 19 26 21" src="https://github.com/Dirt-Road-Development/shiny-octo-giggle/assets/132930012/d7da75be-aa2b-4eb6-84ac-d09c1b5aa825">

- After the slection:

 
<img width="302" alt="Screenshot 2024-04-01 at 19 26 43" src="https://github.com/Dirt-Road-Development/shiny-octo-giggle/assets/132930012/5ae4ac8c-0d68-4d5b-b064-f25da96097cd">

**Comment by TheGreatAxios** [comment]
Resolved by #121
